# Generated by Django 3.1.2 on 2021-08-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210820_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.CharField(default='https://source.unsplash.com/23J7oNGZoRs', max_length=500),
        ),
    ]
