# Generated by Django 3.1.2 on 2021-08-24 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210821_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='icon',
            field=models.CharField(default='NA', max_length=500),
        ),
    ]
